spring.application.name=auth-server
server.port=9000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Random214@#}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6380}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

spring.security.oauth2.authorizationserver.client.auth-server.registration.client-id=auth-server
spring.security.oauth2.authorizationserver.client.auth-server.registration.client-secret={bcrypt}$2a$12$xpNMUk8EYNHPPytzPnz.6..y9BeSEJMyApwpCd2gxfsejYUnPrSnq
spring.security.oauth2.authorizationserver.client.auth-server.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.auth-server.registration.authorization-grant-types=authorization_code,refresh_token
spring.security.oauth2.authorizationserver.client.auth-server.require-proof-key=false
spring.security.oauth2.authorizationserver.client.auth-server.registration.redirect-uris=https://oauth2-gateway-production.up.railway.app/login/oauth2/code/auth-server
spring.security.oauth2.authorizationserver.client.auth-server.registration.scopes=openid,profile

spring.security.oauth2.authorizationserver.client.my-client.token.reuse-refresh-tokens=false
spring.security.oauth2.authorizationserver.client.my-client.token.access-token-time-to-live=5m
spring.security.oauth2.authorizationserver.client.my-client.token.refresh-token-time-to-live=7d

spring.security.oauth2.authorizationserver.keystore.location=classpath:auth-server.jks
spring.security.oauth2.authorizationserver.keystore.password=changeit
spring.security.oauth2.authorizationserver.keystore.alias=auth-server-key

spring.security.oauth2.authorizationserver.client.my-client.registration.post-logout-redirect-uris=${GATEWAY_BASE_URL:http://localhost:8081/}

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.authentication=INFO